### ISSUE TITLE
automatically update

### ISSUE THREAD

**Issue by sandangel** [DxCx/graphql-rxjs#42]
could you add a web hook which will automatically build test and release graphql-rxjs (by CI) every time graphql.js release a new version. Here is some references http://blog.npmjs.org/post/145260155635/introducing-hooks-get-notifications-of-npm

This way you could keep this package up to date with graphql.js with less maintenance effort. I think that you should rewrite the package with typescript so you can have automatically update typing file too.

I have a question that why you not just include graphql.js as a peer dependency? Why do you have to keep a fork of graphql.js when you don't modify any thing at all?

**Comment by DxCx** [comment]
no,
graphql core engine tends to change,
and with each version, i need to rebase upon current upstream,
and make it work again..
at the moment i'm not using it myself, so i'm not rebasing upon newer versions,
but if someone wants to use it on latest i'll be glad to help pick it up again..

**Comment by sandangel** [comment]
Yes. I'm plan to use `@defer` now for my project so could you shed some light for me on this?

**Comment by brysgo** [comment]
@DxCx - What do you use instead?

**Comment by DxCx** [comment]
Well, for each graphql version the patches needs to be rebased, probably modified as well since code progresses..

**Comment by brysgo** [comment]
@DxCx - I was referring to when you said you don't use this anymore, is there something that you use instead of this?

**Comment by DxCx** [comment]
oh,
im not using this not because its not usable or not working, it was working pretty good when i used this..
however im not doing anything that requires a back end at all right now..
if i'll need a backend, GraphQL will be my choice,
and if i need it reactive anyway, i think that this approach works much better and cleaner then existing subscriptions. (unless something change in the past year)
